version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

volumes:
  cudosdappdbdata:
    driver: local

services:
  cudos-aura-platform-dev:
    image: cudos-aura-platform-dev
    container_name: cudos-aura-platform-dev
    build:
      dockerfile: docker/dev/aura-pool-platform.dockerfile
      context: ../../
      args:
        args:
        USER_ID: "$USER_ID"
        USER_NAME: "$USER_NAME"
        GROUP_ID: "$GROUP_ID"
        GROUP_NAME: "$GROUP_NAME"
    restart: unless-stopped
    volumes:
      - '../../:/usr/cudos-aura-platform'
    ports:
      - $HOST_PORT:$DOCKER_PORT
    networks:
      - shared-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on: 
      - cudos-aura-platform-postgres-dev

  cudos-aura-platform-postgres-dev:
    image: postgres
    container_name: cudos-aura-platform-postgres-dev
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_HOST_AUTH_METHOD: "$POSTGRES_HOST_AUTH_METHOD"
      POSTGRES_DB: "$POSTGRES_DB"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - cudosdappdbdata:/var/lib/postgresql/data
    networks:
      - shared-cudos-network

  mailhog:
    image: "mailhog/mailhog"
    container_name: "mailhog"
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - shared-cudos-network
  
  cudos-aura-platform-chain-observer-dev:
    image: cudos-aura-platform-chain-observer-dev
    container_name: cudos-aura-platform-chain-observer-dev
    build:
      dockerfile: docker/dev/chain-observer.dockerfile
      context: ../../
      args:
        USER_ID: "$USER_ID"
        USER_NAME: "$USER_NAME"
        GROUP_ID: "$GROUP_ID"
        GROUP_NAME: "$GROUP_NAME"
        AURA_POOL_BACKEND: "http://cudos-aura-platform-dev"
        CHAIN_ID: "$CHAIN_ID"
        CHAIN_RPC: "$CHAIN_RPC"
        CHAIN_GRPC: "$CHAIN_GRPC"
    restart: unless-stopped
    volumes:
      - '../../:/usr/cudos-aura-chain-observer'
    networks:
      - shared-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on: 
      - cudos-aura-platform-dev

  cudos-aura-platform-eth-payments-relayer:
    image: cudos-aura-platform-eth-payments-relayer
    container_name: cudos-aura-platform-eth-payments-relayer
    build:
      dockerfile: docker/dev/eth-payments-relayer.dockerfile
      context: ../../
      args:
        args:
        USER_ID: "$USER_ID"
        USER_NAME: "$USER_NAME"
        GROUP_ID: "$GROUP_ID"
        GROUP_NAME: "$GROUP_NAME"
        AURA_POOL_BACKEND: "http://cudos-aura-platform-dev"
        CHAIN_ID: "$CHAIN_ID"
        CHAIN_RPC: "$CHAIN_RPC"
        CHAIN_GRPC: "$CHAIN_GRPC"
    restart: unless-stopped
    volumes:
      - '../../:/usr/cudos-aura-eth-payments-relayer'
    networks:
      - shared-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on: 
      - cudos-aura-platform-dev

  cudos-on-demand-minting-service-dev:
    image: cudos-on-demand-minting-service-dev
    container_name: cudos-on-demand-minting-service-dev
    build:
      dockerfile: CudosAuraPoolService/docker/dev/on-demand-minting-service.dockerfile
      context: ../../../
      args:
        USER_ID: "$USER_ID"
        USER_NAME: "$USER_NAME"
        GROUP_ID: "$GROUP_ID"
        GROUP_NAME: "$GROUP_NAME"
        ON_DEMAND_MINTING_STARTING_HEIGHT: "$ON_DEMAND_MINTING_STARTING_HEIGHT"
        AURA_POOL_BACKEND: "http://cudos-aura-platform-dev:$DOCKER_PORT"
        MINTER_WALLET_MNEMONIC: "$MINTER_WALLET_MNEMONIC"
        MINTER_MAX_RETRIES: "$MINTER_MAX_RETRIES"
        MINTER_RETRY_INTERVAL: "$MINTER_RETRY_INTERVAL"
        MINTER_RELAY_INTERVAL: "$MINTER_RELAY_INTERVAL"
        MINTER_PAYMENT_DENOM: "$MINTER_PAYMENT_DENOM"
        MINTER_PORT: "$MINTER_PORT"
        CHAIN_ID: "$CHAIN_ID"
        CHAIN_RPC: "$CHAIN_RPC"
        CHAIN_GRPC: "$CHAIN_GRPC"
        AURA_POOL_API_KEY: "$AURA_POOL_API_KEY"
    restart: unless-stopped
    networks:
      - shared-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: 
      - cudos-aura-platform-dev
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
