version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

volumes:
  cudosdappdbdata:
    driver: local

services:
  cudos-aura-platform:
    image: cudos-aura-platform
    container_name: cudos-aura-platform
    build:
      dockerfile: docker/docker.dockerfile
      context: ../
      args:
        args:
        USER_ID: "$USER_ID"
        USER_NAME: "$USER_NAME"
        GROUP_ID: "$GROUP_ID"
        GROUP_NAME: "$GROUP_NAME"
    restart: unless-stopped
    volumes:
      - '../:/usr/cudos-aura-platform'
    ports:
      - "$HOST_PORT:$DOCKER_PORT"
    networks:
      - shared-cudos-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on: 
      - cudos-aura-platform-postgres

  cudos-aura-platform-postgres:
    image: postgres
    container_name: cudos-aura-platform-postgres
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_HOST_AUTH_METHOD: "$POSTGRES_HOST_AUTH_METHOD"
      POSTGRES_DB: "$POSTGRES_DB"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - cudosdappdbdata:/var/lib/postgresql/data
    networks:
      - shared-cudos-network
