version: '3.1'

networks:
  cudosmarkets-prod-cudos-network:
    name: cudosmarkets-prod-cudos-network

volumes:
  cudosdappdata:
    driver: local

services:
  cudos-markets-platform-prod:
    image: cudos-markets-platform-prod
    container_name: cudos-markets-platform-prod
    build:
      dockerfile: docker/prod/cudos-markets-platform.dockerfile
      context: ../../
    restart: unless-stopped
    ports:
      - "$HOST_PORT:$DOCKER_PORT"
    volumes:
      - ../../../cudosdappdata/cudos-markets-platform:/usr/local/cudos-markets-platform/data
    networks:
      - cudosmarkets-prod-cudos-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"

  cudos-markets-platform-chain-observer-prod:
    image: cudos-markets-platform-chain-observer-prod
    container_name: cudos-markets-platform-chain-observer-prod
    build:
      dockerfile: docker/prod/chain-observer.dockerfile
      context: ../../
      args:
        CHAIN_ID: "$CHAIN_ID"
        CHAIN_RPC: "$CHAIN_RPC"
        CHAIN_GRPC: "$CHAIN_GRPC"
    restart: unless-stopped
    networks:
      - cudosmarkets-prod-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on: 
      - cudos-markets-platform-prod

  cudos-markets-platform-eth-payments-relayer-prod:
    image: cudos-markets-platform-eth-payments-relayer-prod
    container_name: cudos-markets-platform-eth-payments-relayer-prod
    build:
      dockerfile: docker/prod/eth-payments-relayer.dockerfile
      context: ../../
      args:
        CHAIN_ID: "$CHAIN_ID"
        CHAIN_RPC: "$CHAIN_RPC"
        CHAIN_GRPC: "$CHAIN_GRPC"
    restart: unless-stopped
    networks:
      - cudosmarkets-prod-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on: 
      - cudos-markets-platform-prod
