version: '3.1'

networks:
  aurapool-prod-cudos-network:
    name: aurapool-prod-cudos-network

volumes:
  cudosdappdata:
    driver: local

services:
  cudos-aura-platform-prod:
    image: cudos-aura-platform-prod
    container_name: cudos-aura-platform-prod
    build:
      dockerfile: docker/prod/aura-pool-platform.dockerfile
      context: ../../
    restart: unless-stopped
    ports:
      - "$HOST_PORT:$DOCKER_PORT"
    volumes:
      - cudosdappdata:/usr/src/cudos-aura-platform/dist/data
    networks:
      - aurapool-prod-cudos-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"

  mailhog:
    image: "mailhog/mailhog"
    container_name: "mailhog"
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - aurapool-prod-cudos-network
