version: '3.1'

networks:
  aurapool-prod-cudos-network:
    name: aurapool-prod-cudos-network

volumes:
  cudosdappdata:
    driver: local

services:
  cudos-aura-platform-prod:
    image: cudos-aura-platform-prod
    container_name: cudos-aura-platform-prod
    build:
      dockerfile: docker/prod/aura-pool-platform.dockerfile
      context: ../../
    restart: unless-stopped
    ports:
      - "$HOST_PORT:$DOCKER_PORT"
    volumes:
      - ../../../cudosdappdata/aura-pool-platform:/usr/local/cudos-aura-platform/data
    networks:
      - aurapool-prod-cudos-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"

  mailhog:
    image: "mailhog/mailhog"
    container_name: "mailhog"
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - aurapool-prod-cudos-network

  cudos-aura-platform-chain-observer-prod:
    image: cudos-aura-platform-chain-observer-prod
    container_name: cudos-aura-platform-chain-observer-prod
    build:
      dockerfile: docker/prod/chain-observer.dockerfile
      context: ../../
      args:
        CHAIN_ID: "$CHAIN_ID"
        CHAIN_RPC: "$CHAIN_RPC"
        CHAIN_GRPC: "$CHAIN_GRPC"
    restart: unless-stopped
    volumes:
      - '../:/usr/cudos-aura-chain-observer'
    networks:
      - aurapool-prod-cudos-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on: 
      - cudos-aura-platform-prod
