name: Tests

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:platform:prod
    - run: npm run build:backend:prod
    - run: npm run build:chain-observer:prod
    - run: npm run build:frontend:prod
    - run: npx jest collections
    - run: npx jest farm
    - run: npx jest statistics
    - run: npx jest eth-payment-relayer